# Generated by scripts/ci_generate_dockerfile.py
FROM python:3.11-slim-bookworm AS wheel-builder
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /build
RUN python -m ensurepip --upgrade \
    && python -m pip install --upgrade pip setuptools wheel build
COPY example-packages/alpha-lib /src/alpha_lib
RUN python -m pip install -r /src/alpha_lib/requirements.txt \
    && cd /src/alpha_lib && python -m build --wheel -o /out \
    && cp /out/*.whl /build/alpha_lib.whl

FROM python:3.11-slim-bookworm AS svc-http-api
WORKDIR /app
COPY example-services/http-api /app
COPY .docker-reqs-http-api.txt /app/requirements.docker.txt
RUN python -m ensurepip --upgrade && python -m pip install --upgrade pip \
    && python -m pip install --no-cache-dir -r /app/requirements.docker.txt
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

FROM python:3.11-slim-bookworm AS svc-worker
WORKDIR /app
COPY example-services/worker /app
COPY .docker-reqs-worker.txt /app/requirements.docker.txt
COPY --from=wheel-builder /build/alpha_lib.whl /tmp/alpha_lib.whl
RUN python -m ensurepip --upgrade && python -m pip install --upgrade pip \
    && python -m pip install --no-cache-dir /tmp/alpha_lib.whl \
    && python -m pip install --no-cache-dir -r /app/requirements.docker.txt
CMD ["python", "/app/main.py"]
