#!/usr/bin/env python3
"""Erzeugt ./Dockerfile aus modules.json (Multi-Stage: wheels + Services)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ci_lib import (
    all_paths,
    git_path_for_tree,
    load_modules,
    local_package_paths_in_requirements,
    repo_root,
    runtime_requirements_lines,
)


def sh_cmd(cmd: list[str]) -> str:
    return json.dumps(cmd)


def main() -> int:
    root = repo_root()
    modules = load_modules()
    pkgs, svcs = all_paths(modules)
    py_img = modules.get("docker", {}).get("python_image", "python:3.11-slim-bookworm")

    lines: list[str] = [
        "# Generated by scripts/ci_generate_dockerfile.py",
        f"FROM {py_img} AS wheel-builder",
        "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1",
        "WORKDIR /build",
        "RUN python -m ensurepip --upgrade \\",
        "    && python -m pip install --upgrade pip setuptools wheel build",
    ]

    def wheel_slug(pkg_path: str) -> str:
        return Path(pkg_path).name.replace("-", "_")

    for p in pkgs:
        slug = wheel_slug(p)
        gp = git_path_for_tree(p)
        lines.append(f"COPY {gp} /src/{slug}")
        lines.append(
            f"RUN python -m pip install -r /src/{slug}/requirements.txt \\"
        )
        lines.append(
            f"    && cd /src/{slug} && python -m build --wheel -o /out \\"
        )
        lines.append(
            f"    && cp /out/*.whl /build/{slug}.whl"
        )

    for svc in svcs:
        target = modules["docker"]["stage_targets"][svc]
        cmd = modules["docker"]["cmd"][svc]
        req_path = root / svc / "requirements.txt"
        used = sorted(local_package_paths_in_requirements(req_path, root, pkgs))
        slugs = [wheel_slug(p) for p in used]
        svc_slug = Path(svc).name
        gen_req = root / f".docker-reqs-{svc_slug}.txt"
        runtime_lines = runtime_requirements_lines(req_path, root, pkgs)
        gen_req.write_text(
            "\n".join(runtime_lines) + ("\n" if runtime_lines else ""),
            encoding="utf-8",
        )
        lines.append("")
        lines.append(f"FROM {py_img} AS {target}")
        lines.append("WORKDIR /app")
        lines.append(f"COPY {git_path_for_tree(svc)} /app")
        lines.append(f"COPY .docker-reqs-{svc_slug}.txt /app/requirements.docker.txt")
        for slug in slugs:
            lines.append(f"COPY --from=wheel-builder /build/{slug}.whl /tmp/{slug}.whl")
        install_wheels = " && ".join(
            f"python -m pip install --no-cache-dir /tmp/{s}.whl" for s in slugs
        )
        req = bool(runtime_lines)
        parts: list[str] = [
            "python -m ensurepip --upgrade && python -m pip install --upgrade pip"
        ]
        if install_wheels:
            parts.append(install_wheels)
        if req:
            parts.append("python -m pip install --no-cache-dir -r /app/requirements.docker.txt")
        run_body = " \\\n    && ".join(parts)
        lines.append(f"RUN {run_body}")
        lines.append(f"CMD {sh_cmd(cmd)}")

    out = root / "Dockerfile"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
